version: 2

sources:
  - name: stg
    database: test_dev
    tables:
      - name: customers
      - name: ag
        identifier: agents
      - name : product
        freshness: # default freshness
          warn_after: {count: 12, period: day}
          error_after: {count: 24, period: day}
        loaded_at_field: order_date
  - name: stripe
    database: raw
    tables:
      - name: payment