version: 2

sources:
  - name: raw
    database: test
    description: C'est une base avec des raw data
    tables:
      - name: customers
        description: Cette table contient les données clients
        columns:
         - name: id
           tests:
              - not_null
              - unique